
sudo: false
language: node_js
node_js:
- '6'
- '5'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
- npm update
install:
- npm install
before_script:
- npm run clean
script:
- npm test